name: cache
on:
  push:
  pull_request:
  schedule:
    - cron:  '44 4 * * *'
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    steps:
    - uses: actions/checkout@v4
    - uses: ./
      with:
        actions_cache: true
        cvmfs_cache_base: ${{ github.workspace }}/.cvmfs
    - name: Test CernVM-FS
      run: |
        source /cvmfs/sft.cern.ch/lcg/views/LCG_107/x86_64-ubuntu2404-gcc13-opt/setup.sh
        root -l -q -b
